name: Auto Label

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Auto-label PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply labels
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml

  pr-size:
    name: PR Size Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PR Size Labels
        uses: codelytv/pr-size-labeler@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          xs_max_size: "10"
          s_max_size: "50"
          m_max_size: "200"
          l_max_size: "500"
