name: CI - Documentation and Content Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  validate-documentation:
    name: Validate Documentation
    runs-on: self-hosted
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '18'
        
    - name: Install dependencies
      shell: bash
      run: |
        npm install -g markdownlint-cli
        
    - name: Run comprehensive documentation quality checks
      shell: bash
      run: |
        echo "Running comprehensive quality checks..."
        ./scripts/check-documentation-quality.sh
        
    - name: Validate issue templates
      shell: bash
      run: |
        echo "Validating issue templates..."
        
        # Use Python for cross-platform template validation
        python_cmd="python3"
        if ! command -v python3 >/dev/null 2>&1; then
          if command -v python >/dev/null 2>&1; then
            python_cmd="python"
          else
            echo "Error: Python not found"
            exit 1
          fi
        fi
        
        $python_cmd -c "import os,yaml,glob; templates=glob.glob('.github/ISSUE_TEMPLATE/*.yml') if os.path.exists('.github/ISSUE_TEMPLATE') else []; [print(f'✓ Valid YAML: {t}') if yaml.safe_load(open(t,'r',encoding='utf-8')) or True else print(f'✗ Invalid: {t}') for t in templates] if templates else print('No issue templates found')"
        echo "Issue template validation completed"