name: Quality

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  markdownlint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: |
            **/*.md

  links:
    name: Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lychee link check
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose --exclude-mail --accept 200,206 --timeout 20s "**/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          path: .
          ignore_words_list: ue,unreal,behaviour,gameplay,metagame,routemap
          skip: .git,**/sources.bib,**/*.bib
